### ISSUE TITLE
Garb::ClientError: There was an internal error.

### ISSUE THREAD

**Issue by chamnap** [Sija/garb#41]
What should I do with the following error? Do I need to upgrade to use https://github.com/tpitale/legato?

``` ruby
Garb::ClientError: There was an internal error.
/home/ubuntu/.rvm/gems/ruby-2.1.5@yoolk_office/gems/garb-0.9.8/lib/garb/request/data.rb:59:in `handle_response'
/home/ubuntu/.rvm/gems/ruby-2.1.5@yoolk_office/gems/garb-0.9.8/lib/garb/request/data.rb:45:in `send_request'
/home/ubuntu/.rvm/gems/ruby-2.1.5@yoolk_office/gems/garb-0.9.8/lib/garb/management/feed.rb:21:in `response'
/home/ubuntu/.rvm/gems/ruby-2.1.5@yoolk_office/gems/garb-0.9.8/lib/garb/management/feed.rb:13:in `parsed_response'
/home/ubuntu/.rvm/gems/ruby-2.1.5@yoolk_office/gems/garb-0.9.8/lib/garb/management/feed.rb:17:in `entries'
```

**Comment by Sija** [comment]
Hard to say without more data. Could you post your code so I could investigate the issue?
